version: "3"
services:
       backend-server:
           container_name: backend-server
           image: auth-image
           restart: always
           build: .
           ports:
             - "5000:5000"
           links:
             - mongo
       mongo:
             container_name: mongo-container
             image: mongo 
             ports:
               - '27017:27017' 